<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>deliveryEmail</name>
   <tag></tag>
   <elementGuidId>97b91a83-374b-478c-9c44-51b5b7b3a5d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='show_del_delivery_email_label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#show_del_delivery_email_label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d0667bd0-566b-4c52-bdd1-9ffc5a72628a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>show_del_delivery_email</value>
      <webElementGuid>66df673c-bcdf-4565-a4a3-df00bd1f18eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show_del_delivery_email_label</value>
      <webElementGuid>d5661a44-61b3-4c46-9a5b-2a5da4c35c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>820c6d36-2ee8-46cb-a805-bac9d372b58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show_del_delivery_email_label&quot;)</value>
      <webElementGuid>2aa86f36-a515-487d-96e2-7bec0922f909</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='show_del_delivery_email_label']</value>
      <webElementGuid>bb3a36ca-4b42-4e3e-bcd6-d3bd5f247bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[3]/following::label[1]</value>
      <webElementGuid>cbaed65a-de3f-4140-998e-3fcd47e5e1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[3]/following::label[2]</value>
      <webElementGuid>3f5c330f-5391-41f7-847b-5decbd862dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMS'])[1]/preceding::label[1]</value>
      <webElementGuid>240fae5d-5dbb-4bd8-881b-837a9a0e54da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Fields'])[1]/preceding::label[2]</value>
      <webElementGuid>27adf5ea-58c8-430c-bfcb-a7883579de3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/label</value>
      <webElementGuid>b1718e07-4151-4499-80c3-c79d289b68c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'show_del_delivery_email_label' and (text() = 'Email' or . = 'Email')]</value>
      <webElementGuid>d37c50b4-b439-4c33-85d3-52ef8f5d890a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
