<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>deliverySMS</name>
   <tag></tag>
   <elementGuidId>84235672-126a-41e7-afc2-30e0ab68ba22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='show_del_delivery_sms_label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#show_del_delivery_sms_label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>bf863619-e30a-4323-9d3e-6f9a9322a7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>show_del_delivery_sms</value>
      <webElementGuid>76626eaa-8929-426a-a603-8bc032ec7e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show_del_delivery_sms_label</value>
      <webElementGuid>655f5040-ec8a-4449-97d8-067412440cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SMS</value>
      <webElementGuid>8eda99e1-256a-4a26-962c-4758889ef36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show_del_delivery_sms_label&quot;)</value>
      <webElementGuid>7f29f3b7-08d7-49ea-b2c4-913494931cf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='show_del_delivery_sms_label']</value>
      <webElementGuid>d7744fae-04e7-45ce-ac95-9da5d7466a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[3]/following::label[1]</value>
      <webElementGuid>37a10026-21f1-48b7-8be4-ff093a6a1c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[3]/following::label[2]</value>
      <webElementGuid>b5633172-8d23-4094-ab73-cac3b103a44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Fields'])[1]/preceding::label[1]</value>
      <webElementGuid>dff93a90-e16a-4a16-9adf-b1bb026c2d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full'])[1]/preceding::label[1]</value>
      <webElementGuid>e0456b74-baa9-4b02-9bd4-ff12dd8a95aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SMS']/parent::*</value>
      <webElementGuid>cd417efa-62e7-4db7-8299-62ba671244f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div/label</value>
      <webElementGuid>08a50f9d-f61d-4288-8c3a-98757850698c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'show_del_delivery_sms_label' and (text() = 'SMS' or . = 'SMS')]</value>
      <webElementGuid>36005e7e-65f0-4193-94cc-6ab9d8d76e17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
