<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>thirdPartySms</name>
   <tag></tag>
   <elementGuidId>0f3b8e63-9965-4f47-b710-4306ac748a7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='show_tp_collection_sms_label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#show_tp_collection_sms_label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4c33cc7c-a6c5-4103-8274-a13713a6e1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>show_tp_collection_sms</value>
      <webElementGuid>98beeb9e-9a73-454a-a664-dee45d9be35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show_tp_collection_sms_label</value>
      <webElementGuid>cc9b197a-73a9-4512-b8ce-2e15e2c25d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SMS</value>
      <webElementGuid>8960aed7-cb9d-494b-b013-50338c1d5f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show_tp_collection_sms_label&quot;)</value>
      <webElementGuid>f373712d-1ca9-4368-8f53-52cf86eae05a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='show_tp_collection_sms_label']</value>
      <webElementGuid>27d59e92-06aa-4e61-82f8-3cc76878967c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[6]/following::label[1]</value>
      <webElementGuid>df1b9b6b-04e2-48d9-a98b-73c9396f0b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[7]/following::label[2]</value>
      <webElementGuid>a68a665f-f7f4-4f8c-80f4-c1cedf29040b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Fields'])[3]/preceding::label[1]</value>
      <webElementGuid>37af07d7-6f94-4f04-9835-8cbe823af81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full'])[3]/preceding::label[1]</value>
      <webElementGuid>09af030c-201d-422c-9833-8a03ee7d0455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div[4]/div/label</value>
      <webElementGuid>16b605c4-1f87-4400-8f4a-fd5b58ccb6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'show_tp_collection_sms_label' and (text() = 'SMS' or . = 'SMS')]</value>
      <webElementGuid>04fe79fd-4c7e-4b3c-8586-6a6bbbb8f8bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
