<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>thirdPartyEmail</name>
   <tag></tag>
   <elementGuidId>14635bc3-fe75-40de-a0f7-a9382f33aad2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='show_tp_collection_email_label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#show_tp_collection_email_label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ee8ba42f-0fd4-4ccd-a5f3-9a882d1b2981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>show_tp_collection_email</value>
      <webElementGuid>852005df-a3f7-4137-b4ea-7e96b3ef7ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show_tp_collection_email_label</value>
      <webElementGuid>e505de6b-f92f-4975-8d52-ec5fcb64694a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>a63d435e-8c5f-4b2b-86de-a9b9c5af00ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show_tp_collection_email_label&quot;)</value>
      <webElementGuid>a43f5d16-a0f0-435d-a5ed-3ffa637fc642</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='show_tp_collection_email_label']</value>
      <webElementGuid>433b3596-1f45-477f-b6c1-46f518be1945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[7]/following::label[1]</value>
      <webElementGuid>863134b9-24c9-4a76-8749-cae0657498bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[7]/following::label[2]</value>
      <webElementGuid>7964107f-2495-4a1c-b8d0-2fe832d79567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMS'])[4]/preceding::label[1]</value>
      <webElementGuid>9ee95635-e055-451a-8ea8-14cc32eafdd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Fields'])[3]/preceding::label[2]</value>
      <webElementGuid>abd8acce-e910-4215-a797-3387daf0e9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div[3]/div/label</value>
      <webElementGuid>d545ed30-5154-4757-97c4-044bb2226f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'show_tp_collection_email_label' and (text() = 'Email' or . = 'Email')]</value>
      <webElementGuid>af3ecb43-b6d5-47e6-83dd-b76f1a431ef0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
