<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_collection_notes1</name>
   <tag></tag>
   <elementGuidId>670e48f3-2083-4259-99c3-e454fdb70b4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#collection_notes1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='collection_notes1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90d0dd58-89a9-482f-85bd-8c99d0ce9876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba604ccf-8f10-4c55-a734-c54860191668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>collection_notes1</value>
      <webElementGuid>452aff5b-9480-4b26-8e86-b78af6fef45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>collection_notes1</value>
      <webElementGuid>4e28fc8e-3ac7-4804-9604-ade7ee7bcd93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>collectionNotes1</value>
      <webElementGuid>1b93247c-b7ac-418a-b255-321750290ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>c9405c22-fe7c-48d8-83c8-1b9219c7478c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!editColNote1</value>
      <webElementGuid>a4a9eaf2-143d-48de-83e9-fdfb926eecc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-empty ng-valid-maxlength</value>
      <webElementGuid>e91cfa28-7414-4d45-9d72-6f46ccbf667f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection_notes1&quot;)</value>
      <webElementGuid>51f8f524-7024-4907-af3d-a935dda16b3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='collection_notes1']</value>
      <webElementGuid>77ecd6c4-0c16-4d59-8fc7-ec93ec37be02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//notes/ng-form/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>813f3e14-291e-4f2d-9c0e-7184a63c9684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'collection_notes1' and @id = 'collection_notes1']</value>
      <webElementGuid>4526db58-5fca-414c-8529-6d627e4967a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
