<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_delivery_notes1</name>
   <tag></tag>
   <elementGuidId>9b161137-d7fc-4b23-b498-9d948aeb2849</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#delivery_notes1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='delivery_notes1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da39ab4f-b898-403d-98f8-efdd53360036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>411e8512-7997-4191-93f5-c31cd2ec0783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>delivery_notes1</value>
      <webElementGuid>b6e8455d-96da-4ad4-a4e7-db0379cfa712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery_notes1</value>
      <webElementGuid>a3b89182-ff80-40a8-b408-2ca902ea543f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>deliveryNotes1</value>
      <webElementGuid>ce512775-272f-4032-8229-1a2a24db6e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>624ee0cb-e0f4-4352-b08a-ae917dc1a85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!editDelNote1</value>
      <webElementGuid>65240e99-03ec-43fb-afb5-c6d727bcb102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-empty ng-valid-maxlength ng-touched</value>
      <webElementGuid>fa0e2586-3f68-4722-ba19-cc5db94b047a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery_notes1&quot;)</value>
      <webElementGuid>564ceb04-68aa-473c-b612-a611a1e5d6cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='delivery_notes1']</value>
      <webElementGuid>db84c396-ed71-4feb-9fd0-591b71e44535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//notes/ng-form/div/div/div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>6e156716-36b4-4c42-a643-c40f1b6aa106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'delivery_notes1' and @id = 'delivery_notes1']</value>
      <webElementGuid>f209faf7-5aef-4976-a5fa-331dc0da0d58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
