<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_collection_notes3</name>
   <tag></tag>
   <elementGuidId>c4151a94-27c8-4df5-85d7-a7dc8b109664</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#collection_notes3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='collection_notes3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0264219f-80ea-4f78-8ac1-ee9235666f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c011f2ba-d95a-4303-a16f-c2f92f4c5ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>collection_notes3</value>
      <webElementGuid>96e362eb-102d-4373-99ee-a8bbe187a0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>collection_notes3</value>
      <webElementGuid>542608b0-4377-4b72-9483-fbff8b6118e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>collectionNotes3</value>
      <webElementGuid>522c3d20-b4d2-4156-9b7a-e05b8f0898c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>c09a2207-226d-4c48-8c12-7191aeef6498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!editColNote3</value>
      <webElementGuid>1fd83de4-cfbf-4b7b-8d99-b72a31716741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-empty ng-valid-maxlength</value>
      <webElementGuid>305e882b-396f-415b-9566-aecd9d36a54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection_notes3&quot;)</value>
      <webElementGuid>3874f8ca-1f26-48fa-af4e-4db91ddb5a1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='collection_notes3']</value>
      <webElementGuid>e0c4d2cd-9c80-49d7-9316-81369c2d838b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/input</value>
      <webElementGuid>c104b255-c4dd-47d2-a07c-cd21eae562a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'collection_notes3' and @id = 'collection_notes3']</value>
      <webElementGuid>37a2e575-a49f-4615-b9f0-6c68b8ad3cd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
