<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_delivery_notes2</name>
   <tag></tag>
   <elementGuidId>36f8e9db-0bcb-41fc-96d6-dc2a31911bef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#delivery_notes2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='delivery_notes2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a826636-8dbd-4f60-8c38-1484eed779b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7556b8ef-b643-4e09-af91-5dc8d4e776ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>delivery_notes2</value>
      <webElementGuid>a3f1978d-aa8d-4f45-85f0-3785bc692b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery_notes2</value>
      <webElementGuid>e6ffadb3-7bdf-4458-9c6a-d01d5aeda405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>deliveryNotes2</value>
      <webElementGuid>90243b88-45d2-4803-866d-052a28a5e2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>6c2bd1c3-8332-47b1-80b6-d73fd363016e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!editDelNote2</value>
      <webElementGuid>10f4ad40-ccc6-4f75-804e-baf19bafbb7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-empty ng-valid-maxlength</value>
      <webElementGuid>238e6d3e-da34-457d-8183-ef94af4f9939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery_notes2&quot;)</value>
      <webElementGuid>5f74560a-fa55-447d-b21f-ec92a1c3e58d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='delivery_notes2']</value>
      <webElementGuid>8e449e59-fc51-42f3-b72c-79196c64bb3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>23aedf4e-f553-43c5-a232-4f1eda86975a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'delivery_notes2' and @id = 'delivery_notes2']</value>
      <webElementGuid>e67813cc-8f96-4f7c-a50d-7355cc23f5ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
