<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_collection_notes2</name>
   <tag></tag>
   <elementGuidId>788b3a0e-a3a5-4ef8-8346-228a007e07b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#collection_notes2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='collection_notes2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f5afccc-1e85-4eaf-ab03-577c32d5cd5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a458e55b-fba2-4c61-941a-81c863d75282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>collection_notes2</value>
      <webElementGuid>62ebef2e-b2c1-4e43-a13d-6e9d9453238e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>collection_notes2</value>
      <webElementGuid>40c432fd-48ae-4dc9-af04-18f0d115504d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>collectionNotes2</value>
      <webElementGuid>4a738c52-4131-4518-869e-3808c08de070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>269c7276-bf30-4b11-a0e6-72737dde391a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!editColNote2</value>
      <webElementGuid>b0f1e605-b39a-4bce-b717-f62ba7544d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-empty ng-valid-maxlength</value>
      <webElementGuid>625de728-3040-4c0c-a55f-00270fcc6a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection_notes2&quot;)</value>
      <webElementGuid>8bdb8a5e-fe6a-41f4-9313-429e74b5ecd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='collection_notes2']</value>
      <webElementGuid>02170a45-dde1-4327-a8e3-a882d1ec3eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>4fb0e539-bdea-40bc-978f-e34de44b55d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'collection_notes2' and @id = 'collection_notes2']</value>
      <webElementGuid>b6e67c42-ce07-4098-b16e-1670979c941d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
