<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_collection_notes4</name>
   <tag></tag>
   <elementGuidId>a4873f4e-8516-4015-9c62-8b2c468d7e54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#collection_notes4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='collection_notes4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b17df084-06a4-4fee-9077-904edf4f4696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61414411-08a3-4cda-b3e5-d872bc17a02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>collection_notes4</value>
      <webElementGuid>de47b681-9098-492b-bbcc-e41efac53abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>collection_notes4</value>
      <webElementGuid>6df38d17-08f0-413c-8c78-14bfb8430ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>collectionNotes4</value>
      <webElementGuid>da37525d-b4e9-48c2-ab4d-03f095309af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>a72d5679-e945-44c9-a442-d29347708742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!editColNote4</value>
      <webElementGuid>0960fab6-4cd8-42c8-b98e-272cd0212b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-empty ng-valid-maxlength</value>
      <webElementGuid>940410d9-bb22-4901-b8ee-b7cdaf8135c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>ed07a29d-ba83-40be-a260-43a6e96ae55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection_notes4&quot;)</value>
      <webElementGuid>4226d82e-3def-4adc-a3f0-bdd1ec7ecc4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='collection_notes4']</value>
      <webElementGuid>290a06c4-1a71-490b-93b3-e6655e0495e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/input</value>
      <webElementGuid>19dc5b77-5299-4dbe-9320-9acae3b5c84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'collection_notes4' and @id = 'collection_notes4']</value>
      <webElementGuid>3b4f5b60-f8c4-4221-89eb-1271e5e2e1d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
