<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputFull</name>
   <tag></tag>
   <elementGuidId>f65f66cd-95a8-4c5c-8bba-ed425f274e77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#details_full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='details_full']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>447d4ca8-f9b5-41c3-8bf3-3f077afe1e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mask-details-short details-group ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>e1b54be9-fe12-4f3c-9052-4a6b2a0d1d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c1629897-6930-4627-8d77-cdadccf87c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details_full</value>
      <webElementGuid>0f51ba4e-dec5-478f-9b62-b7eac5b5efb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details_full</value>
      <webElementGuid>02a4a465-ec53-400d-ba1d-e79ff2df13a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>spaces.full</value>
      <webElementGuid>00c7f6cc-1c1d-4bf5-99b1-4671d4140cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>spacesUpdated('full')</value>
      <webElementGuid>a660c2ae-9786-45ac-b75a-1c7db70815b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>10980c28-b5fb-4646-8816-b737fa4de77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details_full&quot;)</value>
      <webElementGuid>595c86f4-2a95-41f3-bef9-5671d14e378a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='details_full']</value>
      <webElementGuid>8893fed8-776d-4b7e-9db8-0b59e00fd98a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ptapp-spaces/div/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>1944fa33-2a65-497c-a2ea-38da6ab43829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'details_full' and @id = 'details_full']</value>
      <webElementGuid>f9ef4720-30ad-40eb-8119-0387854b162a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
