<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputOversize</name>
   <tag></tag>
   <elementGuidId>a40236e4-4de7-44e5-a080-e501c7396a24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#details_oversize</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='details_oversize']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c3c40bb-3a16-4431-8d07-d88a40f69359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mask-details-short details-group ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>3087fac8-4824-4a1b-a598-91c6d08adcd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a1ea0d94-3d80-4ac1-bf61-ea15fcf60962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details_oversize</value>
      <webElementGuid>728c5665-98fb-4fc2-9a14-9c681358595d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details_oversize</value>
      <webElementGuid>8cf8e511-5cd5-4fd2-b16b-cc8839ae6a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>spaces.oversize</value>
      <webElementGuid>dcb64543-919d-4ca9-a6e1-55e911464ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4d1160b9-d610-4024-aba1-9be811912339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>spacesUpdated('oversize')</value>
      <webElementGuid>37927f1f-2b15-41e9-8260-d82dcbf0c4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0adbf4c4-552b-4f2b-a3bc-ce6caaf4b5c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details_oversize&quot;)</value>
      <webElementGuid>8c5bc3ef-ca00-4cc1-bc96-1e27f8e5c616</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='details_oversize']</value>
      <webElementGuid>90617720-fe40-4cd8-8f66-f3a6b663f939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>17aa45ec-c41e-4cc4-a604-67a4fee6dd58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'details_oversize' and @id = 'details_oversize']</value>
      <webElementGuid>715fe0b6-eb17-4c8c-8296-38438ecc156c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
