<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputWeight</name>
   <tag></tag>
   <elementGuidId>e829f578-313c-4456-830f-b3d338ad60da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#details_weight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='details_weight']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e54b2509-83f2-4927-a4ea-9cfd2a273a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mask-details ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>881d6308-282e-41cc-8396-df01ef16f8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d061bed7-3b03-4621-96f7-810dc8431788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details_weight</value>
      <webElementGuid>70c398c9-aea2-4648-a6c3-6fa17fed6c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details_weight</value>
      <webElementGuid>a5828cfb-675c-4e10-95c5-1914896acc5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>spaces.weight</value>
      <webElementGuid>2a9cdfa0-c975-4633-b48f-243377daa17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>spacesUpdated('weight')</value>
      <webElementGuid>9ae2a18d-b10c-4bd1-9962-d4a67f61cbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d26651c8-b9fb-4166-8a8f-327bfb9c23fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9f75e7f9-df82-41b1-af27-bb2de330622e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details_weight&quot;)</value>
      <webElementGuid>711e9226-8d72-4dbe-ab84-7e1f21984450</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='details_weight']</value>
      <webElementGuid>fd4ae56e-4bf4-4934-b023-1e4f15da3e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/input</value>
      <webElementGuid>7389ee08-94a7-4065-b908-a0954881b188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'details_weight' and @id = 'details_weight']</value>
      <webElementGuid>7172f74c-c5ee-4c42-9ffc-d8f3f4907515</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
