<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputQuarter</name>
   <tag></tag>
   <elementGuidId>d6c012a9-7305-4052-972f-ef23922bc500</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#details_quarter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='details_quarter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd59cebf-4847-4132-8721-19c2b7fe00ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mask-details-short details-group ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>905e4dd5-9894-414d-83db-f23529cb023f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c479d7e8-f6e2-4416-8793-a2b0cf8a6468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details_quarter</value>
      <webElementGuid>a8c878fc-9179-45b5-88f7-1e1841d538a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details_quarter</value>
      <webElementGuid>190d3c0d-fa20-4c8a-82f1-6fd140e8aa37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>spaces.quarter</value>
      <webElementGuid>1198618c-31ad-4ae4-b60a-26095d10bfee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>spacesUpdated('quarter')</value>
      <webElementGuid>5303d460-b7b3-4fc7-b6e0-9a52fdea056f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8dd43091-2cbb-4abc-9fcf-9156e46102ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details_quarter&quot;)</value>
      <webElementGuid>5354d9d9-6b85-47d8-8e92-07abda4b3235</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='details_quarter']</value>
      <webElementGuid>b995d6a1-1498-4207-af6e-f7e5643531cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/input</value>
      <webElementGuid>7fc0e634-5784-401b-8629-5014330aba81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'details_quarter' and @id = 'details_quarter']</value>
      <webElementGuid>0be6815e-929c-450a-9f87-bfca588a4490</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
