<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputHalf</name>
   <tag></tag>
   <elementGuidId>8bcdf2de-509f-4280-b1b5-2ecc291bfcc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#details_half</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='details_half']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db5225a9-ccf4-436e-803e-003bcc5436e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mask-details-short details-group ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>8861e170-c554-4b24-b79f-fad14b5b042d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e652cf29-cec6-4cd4-ae51-f24c5e804798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details_half</value>
      <webElementGuid>c36ac70f-129e-4d2f-83f3-ca430404c9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details_half</value>
      <webElementGuid>002b2bb6-641b-4ed8-b5fb-7e9d60845b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>spaces.half</value>
      <webElementGuid>5b458e55-8146-4086-9ed2-27b98d80551b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>spacesUpdated('half')</value>
      <webElementGuid>553e44b6-1282-41c8-8e8d-007f91d8b08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>99d770d1-a84d-4e95-87f9-1fdd0420df1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details_half&quot;)</value>
      <webElementGuid>cbccc182-01ae-451b-a11f-26d1721179b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='details_half']</value>
      <webElementGuid>3072cc23-3dac-43bb-b7dc-bd02c5e4b226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ptapp-spaces/div/div/div/div[3]/div/div[2]/input</value>
      <webElementGuid>efc88594-7bcf-4551-9b00-12a33bfeea36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'details_half' and @id = 'details_half']</value>
      <webElementGuid>20a9bfd7-9618-45c2-82b6-22cfc72f82d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
