<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_OS Half</name>
   <tag></tag>
   <elementGuidId>58cf6fb6-b5bd-41f1-aa1c-a41782a146b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#details_os_half</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='details_os_half']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7412ff1-8dd8-4e7b-9426-3ab0baaaacaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mask-details ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>3ed0a0e0-2c1d-48cd-a060-ac13d465f002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc05ae81-a73b-48ab-a776-8fb69602315c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details_os_half</value>
      <webElementGuid>35e987c7-fd72-494a-bb72-ea6bb7c1e9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details_os_half</value>
      <webElementGuid>7bdd57b3-18e9-42e9-9e43-4e22e2606986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ed0c1132-5521-4869-96c9-779ef655aae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>spaces.osHalf</value>
      <webElementGuid>a3d460ff-9931-47a3-a85a-be07fa1c9df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>spacesUpdated('osHalf')</value>
      <webElementGuid>e1095e28-3105-452b-b551-8b69f8b44c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5ca87931-5da7-4006-818a-95a3e68af98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c1cd100b-071b-4297-95b5-87d451f3a0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>11780310-fc53-4fe2-ac40-b2b399225560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details_os_half&quot;)</value>
      <webElementGuid>5c351c3b-7d10-4d77-a300-2c571ab017e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='details_os_half']</value>
      <webElementGuid>572aa96e-a09d-43ae-8940-5e117be53207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form__oversize-fields']/div/div[3]/div/div[2]/input</value>
      <webElementGuid>d2723732-75f2-438f-a3c2-c6de4a06ce2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>a9de820b-47c3-4a04-b839-983c10f758c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'details_os_half' and @id = 'details_os_half' and @placeholder = '0']</value>
      <webElementGuid>8fadae2c-e426-4a0c-acc7-0b55e03c1cdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
