<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputOSFull</name>
   <tag></tag>
   <elementGuidId>30df6bcd-6039-47a3-87e4-9576e8cf1ad8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#details_os_full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='details_os_full']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec21ef4c-003f-41ae-bbbb-1307aefd2ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mask-details ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>543b66e4-2cb3-4825-80e5-1eb253e6b70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d1ce4d0-b020-4cca-85e5-b69bc76d0f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details_os_full</value>
      <webElementGuid>5e673143-9e7a-43db-905e-20d26e8b20fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details_os_full</value>
      <webElementGuid>afceda34-892e-4220-90a4-bc42812dcb0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dd5783c5-d395-4d5d-8139-62f27b60432e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>spaces.osFull</value>
      <webElementGuid>fe5baa8a-5e87-45a0-a240-340d7ff14d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>spacesUpdated('osFull')</value>
      <webElementGuid>e78ad1ce-bd5c-49ed-9fc7-92bef3678e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>fa9e1cd7-f27a-4a68-abe6-561ccdcda41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b8454964-7f1f-4af4-9254-835cadabfb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details_os_full&quot;)</value>
      <webElementGuid>b7b48053-34d2-4b4f-a810-d4c73e8782c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='details_os_full']</value>
      <webElementGuid>aa90b85e-6335-40af-a450-d84952613733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form__oversize-fields']/div/div[2]/div/div[2]/input</value>
      <webElementGuid>69427d95-96b9-4860-90e7-ecb6b6465932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>9974f310-1d4b-4657-97db-45eb27cd8178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'details_os_full' and @id = 'details_os_full' and @placeholder = '0']</value>
      <webElementGuid>a3955032-5ff1-49b5-98fb-b5390f2178c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
