<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_OS Quarter</name>
   <tag></tag>
   <elementGuidId>e57da612-0987-4e47-9bf1-a389e907e082</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#details_os_quarter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='details_os_quarter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13501bc1-09df-467f-bfc9-b5164b4d985a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mask-details ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>88705a84-a4c7-4d36-9682-64962af1f264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b40e2bbb-04c6-4a84-8342-d35b736f6f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details_os_quarter</value>
      <webElementGuid>4736db8f-8766-44b7-bfcc-5226e6a5575f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details_os_quarter</value>
      <webElementGuid>46c9b302-d36a-41f4-a526-01c25b34c7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f3fe75c3-9995-4ff5-b3f7-bcbf91b6491e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>spaces.osQuarter</value>
      <webElementGuid>973174a6-0e83-44a9-a6d2-ec023797d70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>spacesUpdated('osQuarter')</value>
      <webElementGuid>65be4d56-1819-47f7-9a00-31f7f359fae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>947c9698-d954-4dc2-a0e6-704dafc61b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>60960d51-25e8-4660-8916-ef3b43f1f587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d9f802be-db82-42f7-ac78-a7268736af1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details_os_quarter&quot;)</value>
      <webElementGuid>1a5bef19-9bd6-473d-b81a-4fc56f648322</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='details_os_quarter']</value>
      <webElementGuid>23449979-6506-4663-a3a6-53d6570225a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form__oversize-fields']/div/div[4]/div/div[2]/input</value>
      <webElementGuid>4c057f7e-07e6-4ffd-8400-a46d74b25229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/div[2]/input</value>
      <webElementGuid>683f3ace-8b66-4303-86c9-adcf54669fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'details_os_quarter' and @id = 'details_os_quarter' and @placeholder = '0']</value>
      <webElementGuid>6cf42e1d-9939-4f00-8e7b-4eaa4c536470</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
