<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputSpecificTime</name>
   <tag></tag>
   <elementGuidId>0310cec9-389d-4c41-91da-f478a6661723</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#specific_time</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='specific_time']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f980a1a-7dae-48f1-807c-614eb8986647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mask-time ng-pristine ng-untouched ng-valid ng-empty ng-valid-required</value>
      <webElementGuid>ce16e589-9ef3-432c-8c8c-fd138eed9b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33f84db6-c0fb-4b23-8c8a-66fb5ef12d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>specificTime</value>
      <webElementGuid>7cc9efde-8702-44f1-b5eb-34e2e84128d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>specific_time</value>
      <webElementGuid>795d61cd-fedb-4dea-917a-ea800ddc04df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>specific_time</value>
      <webElementGuid>a8d039f9-5f17-4b32-bf2a-ecfa6bb79210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>10:00 - 17:00</value>
      <webElementGuid>036b2e54-51d1-4e03-9ea9-27003dd2e3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2cd08a31-b8f8-4255-af67-6c124643b74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>specificTimeUpdated()</value>
      <webElementGuid>7e6ecb41-0d9b-495c-8d47-30f0e6b712a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>27ef3607-8c0b-4a85-a4ba-0a9a55c01f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;specific_time&quot;)</value>
      <webElementGuid>e2e9d827-3f0e-40ad-a3bf-9dba56431e8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='specific_time']</value>
      <webElementGuid>67a8b89d-03cc-4efd-80a0-9658199549bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/input</value>
      <webElementGuid>109aedac-933e-43ce-86a9-593f47ce9ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'specific_time' and @id = 'specific_time' and @placeholder = '10:00 - 17:00']</value>
      <webElementGuid>e539bceb-e16a-4c5b-bb44-14caf197ede0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
