<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_OS Spaces</name>
   <tag></tag>
   <elementGuidId>e409cd40-8de7-4493-9e3e-c6baa0494813</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#details_os_spaces</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='details_os_spaces']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88a6b320-ce7b-4aa7-8dc1-56d028742cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a4266937-36c2-4240-9b87-9d7615fc4db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details_os_spaces</value>
      <webElementGuid>68127a4d-41ec-431d-a15b-f9540855e287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details_os_spaces</value>
      <webElementGuid>33e77e8a-9902-4bef-9c67-5daa1afd2eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>spaces.totalOsSpaces</value>
      <webElementGuid>2652e148-d83d-44b9-8699-cca879337a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cb38ce6d-26ba-4519-aa7d-0de955666e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>2e9d733c-63d8-448e-813a-221380f56b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details_os_spaces&quot;)</value>
      <webElementGuid>40acc5f5-7a97-4612-9516-4cb0b0f7436e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='details_os_spaces']</value>
      <webElementGuid>cf5bb851-40d2-4111-9c4e-16b73e0e5a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form__oversize-fields']/div/div[5]/div/div[2]/input</value>
      <webElementGuid>c4b2c3a1-1523-4db1-b3c6-fd117468e94c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]/div/div[2]/input</value>
      <webElementGuid>bdab0811-0f88-4203-93e8-3b833549419a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'details_os_spaces' and @id = 'details_os_spaces']</value>
      <webElementGuid>a8728c29-9e3d-4b8e-a460-2097e1b8051b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
