<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectDueTime</name>
   <tag></tag>
   <elementGuidId>4a6284ea-155a-48c0-b16c-205e29918303</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#timed_surcharge</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='timed_surcharge']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>475f5675-d734-49dd-ba94-487d4374b21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>timed_surcharge</value>
      <webElementGuid>b4abb86b-4e97-4d75-8fcd-f2b43455caa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>timed_surcharge</value>
      <webElementGuid>93fbb9a7-f9fd-40c1-b119-7d474508a4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>timedSurcharge</value>
      <webElementGuid>db73ee88-246a-48bf-891b-7c028cf1896e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>timedSurchargeUpdated()</value>
      <webElementGuid>78574ca2-b3d1-4927-a3a7-d2b3e4535690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-valid ng-not-empty ng-touched ng-dirty ng-valid-parse</value>
      <webElementGuid>e149cc17-3980-45bc-a926-df2492de30ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Anytime (From 09:00 - 17:00)AM (Between 09:00 - 12:00 Week Day)PM (Between 12:00 - 17:00 Week Day)Time Specific (At The Time Entered -10am or later)
                                </value>
      <webElementGuid>6893290c-05e0-4984-8afa-f1394c61ce3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timed_surcharge&quot;)</value>
      <webElementGuid>f46bbde2-dfe5-4cec-b344-dcc4df726d27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='timed_surcharge']</value>
      <webElementGuid>9dd69b71-0fae-478a-85c8-af9c1c6dc6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deliveryTimeSelect']/div/div[2]/div/select</value>
      <webElementGuid>fc3ae93e-40c9-460f-976e-fc452b2c3855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Time'])[1]/following::select[1]</value>
      <webElementGuid>c62ba444-7a3f-4abd-9494-fdb8b1dd5127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Date'])[1]/following::select[2]</value>
      <webElementGuid>01f83cf0-3413-4ed1-9db9-b6475fbb2e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter time between 10:00 - 17:00'])[1]/preceding::select[1]</value>
      <webElementGuid>283903fd-c0b9-464d-9013-bfb24b0b2819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Driver call in advance'])[2]/preceding::select[1]</value>
      <webElementGuid>f7622fbd-5a20-4b5f-b4e9-0d110b328216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/select</value>
      <webElementGuid>61a04f81-39c4-4371-bc9b-885492018944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'timed_surcharge' and @id = 'timed_surcharge' and (text() = '
                                    Anytime (From 09:00 - 17:00)AM (Between 09:00 - 12:00 Week Day)PM (Between 12:00 - 17:00 Week Day)Time Specific (At The Time Entered -10am or later)
                                ' or . = '
                                    Anytime (From 09:00 - 17:00)AM (Between 09:00 - 12:00 Week Day)PM (Between 12:00 - 17:00 Week Day)Time Specific (At The Time Entered -10am or later)
                                ')]</value>
      <webElementGuid>c2acb741-a3ef-45df-a087-ca6dda37e4ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
