<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectDueDate</name>
   <tag></tag>
   <elementGuidId>b71e6b60-e862-4923-b6bd-803fd35c2c0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#delivery_specific_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='delivery_specific_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>91ed936c-9e3b-4cff-bf3b-b43ae92bccad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>delivery_specific_date</value>
      <webElementGuid>6568c340-97b3-4f85-9631-42706adeb792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery_specific_date</value>
      <webElementGuid>d18637c3-2cbb-4f3d-9de5-91edfa8af3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>specificDate</value>
      <webElementGuid>8c203ebf-ca5e-4e81-98ef-d45fb9304bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>specificDateUpdated()</value>
      <webElementGuid>60f65c8a-18ef-4e72-af98-2799cc3cdf5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>ff65d423-7746-4ec3-ba9f-5d666d2c0741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                01/07/2022
                            </value>
      <webElementGuid>956ddce0-404d-49fe-99aa-e1f6a7e98a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery_specific_date&quot;)</value>
      <webElementGuid>4a284f79-1071-4814-97fd-011c36527a8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='delivery_specific_date']</value>
      <webElementGuid>f7b1a9a0-9de1-438d-b9b1-81929a10f0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Date'])[1]/following::select[1]</value>
      <webElementGuid>30837907-b755-489f-9a83-84e4c43f6938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service'])[1]/following::select[2]</value>
      <webElementGuid>c29d07f8-0515-46ba-9131-eebdde7c5743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Time'])[1]/preceding::select[1]</value>
      <webElementGuid>087fb76f-84df-4c53-a3ee-29ebe3e2ae7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter time between'])[1]/preceding::select[2]</value>
      <webElementGuid>02277c10-b2f4-4e91-9f62-41d63044344d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/select</value>
      <webElementGuid>e5c71846-8adf-43ae-b161-0b08022f3ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'delivery_specific_date' and @id = 'delivery_specific_date' and (text() = '
                                01/07/2022
                            ' or . = '
                                01/07/2022
                            ')]</value>
      <webElementGuid>48d188db-42b2-4a42-8364-b93321e36482</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
