<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addr4</name>
   <tag></tag>
   <elementGuidId>54f10b8a-e84f-4272-a5f0-cafabb01e821</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='delivery_delivery_fields_addr4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#delivery_delivery_fields_addr4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2cf67072-5c5c-4247-86ed-743def94e315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4fc4bb90-7d61-436d-aad6-f0841bbf9327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fields_addr4</value>
      <webElementGuid>9e7893b0-90f0-4452-8278-7fb3b2985aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/[A-Za-z0-9/*-_.,&amp;'()+/]+$/</value>
      <webElementGuid>c34c9a04-c8b8-46b0-8c82-5437d38b49f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery_delivery_fields_addr4</value>
      <webElementGuid>af65ee67-c884-4896-a10a-2c77c7b69c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>County / State</value>
      <webElementGuid>55b48c9d-8fcc-4d31-848b-6b8acbfd0d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>fields.add4</value>
      <webElementGuid>5fcf008d-8eab-489f-b473-fd0a09d9c612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>e9fbaa89-9840-4f8f-90d7-d27c1141b2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>searchAddFieldDisable('add4')</value>
      <webElementGuid>210cf6bf-afb3-4d2b-a3e6-c8a0666a9f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>validation.fields_addr4.required</value>
      <webElementGuid>448b5198-ea12-4d9e-adc5-2a36ffdd4844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid-pattern ng-valid-maxlength ng-not-empty ng-valid ng-valid-required</value>
      <webElementGuid>60826e90-06bd-4e13-ad38-1da56bed8cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>3fa9cba8-c2ad-4721-87dd-9b5eac5036d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery_delivery_fields_addr4&quot;)</value>
      <webElementGuid>68e4d20f-4651-47a1-99ee-5c92adf1f76f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='delivery_delivery_fields_addr4']</value>
      <webElementGuid>4523c3a3-fddb-4f99-a524-de45635e700d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ptapp-address-master/ng-form/div/div[2]/div/div/div[2]/ptapp-address-fields/ng-form/div/div/div/div/div/div[2]/div[5]/input</value>
      <webElementGuid>63ec3067-6444-47bb-b8fb-62ad83dffcb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fields_addr4' and @id = 'delivery_delivery_fields_addr4' and @placeholder = 'County / State']</value>
      <webElementGuid>9e9d17b4-64c4-43ed-870e-4660b662fc2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
