<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addr3</name>
   <tag></tag>
   <elementGuidId>6c4cafef-a27e-4f12-adac-2111ce02a4f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='delivery_delivery_fields_addr3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#delivery_delivery_fields_addr3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67d74136-3d67-4a61-a5eb-7335e6ff3e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41828758-4fa3-4d85-8a49-08d5310deb68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fields_addr3</value>
      <webElementGuid>d8d0be5a-5c21-487c-94a1-f7c555c550d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/[A-Za-z0-9/*-_.,&amp;'()+/]+$/</value>
      <webElementGuid>656b9388-e4a1-4bd9-b9b7-fc530b94b6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery_delivery_fields_addr3</value>
      <webElementGuid>a52f696a-ed4a-442a-8e23-b10b28c659b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Town / City</value>
      <webElementGuid>a2d52b95-4215-4739-8ae2-6d450e01d4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>fields.add3</value>
      <webElementGuid>38a1bd7f-5a4c-4a31-9a8b-7ead9f6d8172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>3ae1d0e7-ff02-463a-bdc5-31cf3dd2b8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>searchAddFieldDisable('add3')</value>
      <webElementGuid>79ab0643-054b-412e-8e7c-4cc4852642a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>postcodeCityValidation()</value>
      <webElementGuid>b91231db-0a78-4b2b-8b22-2450444327c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>validation.fields_addr3.required</value>
      <webElementGuid>002b745e-d103-4d44-9314-eedf699cf849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid-pattern ng-valid-maxlength ng-valid-addr3 ng-not-empty ng-valid ng-valid-required</value>
      <webElementGuid>866d695d-00b5-4a96-aa49-3ce349ac75c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>4677ca9a-19a9-41e9-aaf6-61dc2dd18040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery_delivery_fields_addr3&quot;)</value>
      <webElementGuid>83bfe41a-17dd-49da-bb64-52324ad26745</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='delivery_delivery_fields_addr3']</value>
      <webElementGuid>96867cb3-05d5-4f32-b07f-cb61e5b1340c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ptapp-address-master/ng-form/div/div[2]/div/div/div[2]/ptapp-address-fields/ng-form/div/div/div/div/div/div[2]/div[4]/input</value>
      <webElementGuid>031f9d4e-d2aa-48f0-8cb5-bc392f193f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fields_addr3' and @id = 'delivery_delivery_fields_addr3' and @placeholder = 'Town / City']</value>
      <webElementGuid>80691480-028e-4a4c-8eb8-b7a84fde7198</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
