<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Complete Delivery</name>
   <tag></tag>
   <elementGuidId>8a6c5caa-4c67-4965-a945-b125ebd60f5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='delivery_deliverycompleteBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#delivery_deliverycompleteBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81e24ca8-4012-4fbc-a1f9-71cca612cfe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>$ctrl.showExtra == false</value>
      <webElementGuid>99cdc98a-427e-4103-b947-d7bf76e741d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>complete()</value>
      <webElementGuid>b2382f85-f03c-4ff0-9de8-72d816a511d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button ng-scope</value>
      <webElementGuid>29b79445-29b2-4765-a852-1d71045f57ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery_deliverycompleteBtn</value>
      <webElementGuid>eba4d774-9334-4c0a-8b67-63082f2325ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Complete</value>
      <webElementGuid>8c5f70be-3e30-40f9-89f2-ee667211c925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery_deliverycompleteBtn&quot;)</value>
      <webElementGuid>ef8e9fa5-92a3-41cb-828f-7eb39f30bb98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='delivery_deliverycompleteBtn']</value>
      <webElementGuid>ea9977b5-bbd9-4d1d-90ba-99b465fdf830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Complete')])[2]</value>
      <webElementGuid>6e642d02-9ea6-403d-90f3-5b66757b944d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember This Address'])[1]/following::a[1]</value>
      <webElementGuid>55e78409-0172-4651-8cc1-40444d83565d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Address'])[1]/following::a[2]</value>
      <webElementGuid>be80ba5a-3972-42fb-bcdf-484565679205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[39]</value>
      <webElementGuid>e44b243f-8350-4b2a-bfae-b33a32ac2847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ptapp-address-buttons/div/a[3]</value>
      <webElementGuid>028e8da9-cad8-4679-be42-5a11f256231f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'delivery_deliverycompleteBtn' and (text() = ' Complete' or . = ' Complete')]</value>
      <webElementGuid>8f836b88-4a6f-4873-a969-9e3304fe55e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
