<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>contact</name>
   <tag></tag>
   <elementGuidId>1393fde2-0ac1-4cad-8167-cb62c858dfc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='delivery_delivery_fields_contact']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#delivery_delivery_fields_contact</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>361b62e6-92a2-4d05-b9ee-30422339eda9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f59d40d0-9700-4ac0-ae3f-b14afb56ac71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/[A-Za-z0-9/*-_.,&amp;'()+/]+$/</value>
      <webElementGuid>f7eb8621-62e8-4280-95dc-08a9424235f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fields_contact</value>
      <webElementGuid>8f243cae-5a8d-418a-a63e-c552703ccc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery_delivery_fields_contact</value>
      <webElementGuid>4a2ebc9a-d011-468d-a2cd-7e7a2d80c1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>fields.contact</value>
      <webElementGuid>97bb254b-e2ca-44f6-9094-222e91a75245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>64ae0242-ca16-4df8-bbd9-f4649d973f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>validation.fields_contact.required</value>
      <webElementGuid>ed2ea638-0e5b-4bae-9bfa-a2a5dd9d3642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-empty ng-valid-pattern ng-valid-maxlength ng-valid-required</value>
      <webElementGuid>a27b6142-d46b-45b5-9b44-0b65d2e3f406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery_delivery_fields_contact&quot;)</value>
      <webElementGuid>986a02d8-34ed-41ff-93ab-93dced850392</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='delivery_delivery_fields_contact']</value>
      <webElementGuid>6a6e22dd-175d-401a-9136-85d1321a8bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ptapp-address-master/ng-form/div/div[2]/div/div/div[2]/ptapp-address-fields/ng-form/div/div/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>cf5eac0e-6d3e-4092-9487-fe259c86606a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fields_contact' and @id = 'delivery_delivery_fields_contact']</value>
      <webElementGuid>56417b7b-d279-4f1c-bab0-9ddcdaef2666</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
