<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>country</name>
   <tag></tag>
   <elementGuidId>b4cb1f0d-41bf-42bd-a574-b738acccf0b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='delivery_delivery_fields_country']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#delivery_delivery_fields_country</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3ae41050-b898-4046-9a21-f1687b640a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fields_country</value>
      <webElementGuid>eec38dc7-3962-4f56-86fb-b581ca83eb8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery_delivery_fields_country</value>
      <webElementGuid>d75d80ef-4e6f-4cec-a5a5-eb51ebeb3ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>fields.country</value>
      <webElementGuid>380cfcb9-6949-421d-9a85-d1bc9717ad5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>c for c in countries</value>
      <webElementGuid>571257d5-8925-4bff-8bb2-a1b7f84c390d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>countryChanged()</value>
      <webElementGuid>26968112-3e54-447a-928b-e9997a80bd0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>searchAddFieldDisable('country')</value>
      <webElementGuid>4c3687d7-fb6f-400a-bdb7-f54a735fd26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>b00212d5-df26-43c0-a59b-c52a9e91bf47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GBRAUSBELBGRCHEHRVCZEDEUDNKESPESTFRAFINGRCHUNITALUXLTUNORNLDPRTPOLROURUSSWESVKSVNLVAUKRBLRGEOAZEKAZIRL</value>
      <webElementGuid>2de42428-4fea-4064-9a94-2b5118c44708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery_delivery_fields_country&quot;)</value>
      <webElementGuid>8ad52e34-fd52-4721-b9dc-2e0d9a33141b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='delivery_delivery_fields_country']</value>
      <webElementGuid>4548c633-a9a6-402a-a1d4-3915da619043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>6fefa8b7-7924-4e3c-a715-f131be107b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[2]/preceding::select[1]</value>
      <webElementGuid>ee981d60-0708-4047-8e8e-659a46934b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[2]/preceding::select[1]</value>
      <webElementGuid>f4549e7b-b585-43c3-8f76-867c6c757bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ptapp-address-master/ng-form/div/div[2]/div/div/div[2]/ptapp-address-fields/ng-form/div/div/div/div/div/div[2]/div[7]/div/select</value>
      <webElementGuid>7749b63b-c75f-4e44-b49e-4301d5200939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fields_country' and @id = 'delivery_delivery_fields_country' and (text() = 'GBRAUSBELBGRCHEHRVCZEDEUDNKESPESTFRAFINGRCHUNITALUXLTUNORNLDPRTPOLROURUSSWESVKSVNLVAUKRBLRGEOAZEKAZIRL' or . = 'GBRAUSBELBGRCHEHRVCZEDEUDNKESPESTFRAFINGRCHUNITALUXLTUNORNLDPRTPOLROURUSSWESVKSVNLVAUKRBLRGEOAZEKAZIRL')]</value>
      <webElementGuid>66369bb5-568b-4d31-9908-927a3f2870ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
