<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>postcode</name>
   <tag></tag>
   <elementGuidId>6db010d1-1090-4867-8d56-ba43a185b7f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='delivery_delivery_postcode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#delivery_delivery_postcode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a154c5bd-81f9-4e43-8a74-49b757e28f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>48788743-71ca-4d6e-be4c-ea0f904d5530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fields_postcode</value>
      <webElementGuid>a2d19461-94bb-4200-900d-d5d31f2733e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-placeholder</name>
      <type>Main</type>
      <value>{{ fields.country === 'GBR' || fields.country === 'IRL' ? 'Postcode *' : 'Zipcode *' }}</value>
      <webElementGuid>dd3f9b31-067d-48f0-9957-8a8def15a301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>fields.postcode</value>
      <webElementGuid>ec0940d4-9e1f-411d-812f-5cbdb2fe2997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>postcodeChanged()</value>
      <webElementGuid>ea901846-8275-4718-aa9c-927d01a0e3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>{ debounce: 500 }</value>
      <webElementGuid>0ff733b0-ed55-4072-9585-5b9e651f89e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>validation.fields_postcode.required</value>
      <webElementGuid>b6f7e4a5-5d00-4d4e-891b-32a02abd3dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>searchAddFieldDisable('postcode')</value>
      <webElementGuid>5c408fb3-37f4-4e31-973f-0b68b066a830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/[A-Za-z0-9/*-_.,&amp;'()+/]+$/</value>
      <webElementGuid>a38d7b23-cf24-4943-9838-1003cfac798f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery_delivery_postcode</value>
      <webElementGuid>e006c711-de73-4aa3-8fad-6c12c36b01a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid-pattern ng-valid-fields_postcode ng-not-empty ng-valid ng-valid-required ng-valid-postcode</value>
      <webElementGuid>438d81bc-1292-46a7-b52d-34e4618c7275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Postcode *</value>
      <webElementGuid>8823f0a5-c68c-431b-999d-1d47ee331335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>a9e9a9e5-4d62-449c-ae95-68be1c5cd5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery_delivery_postcode&quot;)</value>
      <webElementGuid>d64c53a8-e5b8-4f80-aa20-782b6f5496c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='delivery_delivery_postcode']</value>
      <webElementGuid>db233fdd-4d95-469f-9071-890c4040bce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ptapp-address-master/ng-form/div/div[2]/div/div/div[2]/ptapp-address-fields/ng-form/div/div/div/div/div/div[2]/div[6]/input</value>
      <webElementGuid>3e4efed3-3915-4048-87fb-48672207cdd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fields_postcode' and @id = 'delivery_delivery_postcode' and @placeholder = 'Postcode *']</value>
      <webElementGuid>379d3990-d5be-4f08-8a5c-847b495bedc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
