<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Reset Btn</name>
   <tag></tag>
   <elementGuidId>2b52ba81-3573-4c39-953c-d9580e003b52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='delivery_deliveryresetBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#delivery_deliveryresetBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e11ef89c-1391-4f88-8a24-038d3d98b3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>$ctrl.viewConfig.isSelectOnly == false</value>
      <webElementGuid>6d08c54a-a21e-43bf-ade8-37cd9af09624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>reset()</value>
      <webElementGuid>30617e7d-eb20-4191-8b25-6b053c45bbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--secondary ng-scope</value>
      <webElementGuid>040351dd-06e9-4c03-9d2a-60bb83cf26d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery_deliveryresetBtn</value>
      <webElementGuid>5939fd6f-e8b8-4c6e-8c8c-7bdbdc44b7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Reset Address</value>
      <webElementGuid>7755cdf8-e148-4d40-95f0-1dc149f6c6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery_deliveryresetBtn&quot;)</value>
      <webElementGuid>4af5759c-db18-4185-89fe-51b9725b0711</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='delivery_deliveryresetBtn']</value>
      <webElementGuid>1b6f1cc9-3e44-4b92-a87e-394d7ffa1914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Reset Address')]</value>
      <webElementGuid>479e5a3c-c70c-4918-84e7-caa4a59aa030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You are editing existing address , Pressing Save and Complete will overwrite the existing address'])[1]/following::a[1]</value>
      <webElementGuid>af817876-e66c-4b8b-9000-5117bafd58d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default Address Notes'])[2]/following::a[1]</value>
      <webElementGuid>b2af5305-8409-4ca3-9102-b1c665b66c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember This Address'])[1]/preceding::a[1]</value>
      <webElementGuid>6c67ed8e-2b90-4bd5-a628-51d15a6d71fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complete'])[2]/preceding::a[2]</value>
      <webElementGuid>30d2eb5a-122f-4f7a-bd5d-9932b69078d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reset Address']/parent::*</value>
      <webElementGuid>915b6506-474d-4f6c-9cc0-5483df64b89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[37]</value>
      <webElementGuid>d2e0ed0f-4fd8-4d04-9101-1082a32889b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ptapp-address-buttons/div/a</value>
      <webElementGuid>7f713b0d-4309-4e2d-b624-315008376e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'delivery_deliveryresetBtn' and (text() = ' Reset Address' or . = ' Reset Address')]</value>
      <webElementGuid>10228ccd-9c00-4a6c-bcd1-b7b8fd5e3e58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
