<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sms</name>
   <tag></tag>
   <elementGuidId>e9ad0f34-b871-407c-931d-98bbbe700add</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='delivery-phoneNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#delivery-phoneNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca245ff3-52ab-4721-b05b-7d1f6a5ba68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f78c5b5a-329c-47e0-806e-26415c7f5588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7f12abc8-93b5-4ff7-a50e-011cef92470c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery-phoneNumber</value>
      <webElementGuid>2a1eb046-28d1-4f6a-b76b-6daa33c27464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>smsModel.smsNumber</value>
      <webElementGuid>e30c8738-cbc9-4117-856d-688e51c33e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>{ debounce: 50 }</value>
      <webElementGuid>6b931e10-c166-4d92-af80-7f90d2fc9539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>0b54b082-5d6e-4dc3-8962-7697f640b16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>sms number</value>
      <webElementGuid>e87743b7-2c68-4bdf-9537-f91b7f3fa8df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>validate()</value>
      <webElementGuid>47a807b3-7a38-482b-9216-c3fab0e8cf41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>smsNumberFocused()</value>
      <webElementGuid>399ef753-6cb1-4981-9207-b484d92a2787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>smsModel.required</value>
      <webElementGuid>0be055de-447c-4446-90a5-906ab5c5b12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-empty ng-valid-maxlength ng-valid-required</value>
      <webElementGuid>8173dd17-dd77-4020-ae6c-e2f48b3b14a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>231f222e-bc3c-43df-a2c5-4f56c3d0ce87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-intl-tel-input-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>91a0c6be-f496-49ac-a397-b5185190705e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery-phoneNumber&quot;)</value>
      <webElementGuid>818061f4-598f-486a-a78f-03e116960d75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='delivery-phoneNumber']</value>
      <webElementGuid>5dda5812-74f2-4f7a-86cd-f9c62ddc8cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-form/div/div[2]/div/input</value>
      <webElementGuid>c5029199-16ca-48f8-a936-f22e6af85cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'number' and @id = 'delivery-phoneNumber' and @placeholder = 'sms number']</value>
      <webElementGuid>5ef1da83-358c-4079-b109-77cc54f2d927</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
