<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Customer_Reference</name>
   <tag></tag>
   <elementGuidId>0664eaf1-6385-4607-aaf5-689e4cf3e19e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer_reference']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customer_reference</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>608560ef-9cdb-480b-a127-25550b1e45cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7e2d9994-01af-439a-81ed-70f90592c563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer_reference</value>
      <webElementGuid>2e809fc0-78bd-4316-bd7e-fe1ad8cde94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_reference</value>
      <webElementGuid>a23af66b-ee58-4abf-9e20-64256f7dbd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Customer Reference</value>
      <webElementGuid>2a600045-8be0-49f4-ae61-13db67aa325b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>customerReference</value>
      <webElementGuid>2eddab44-7208-4a05-a135-b02844d49d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>01fdb562-444c-4f32-93cc-55db683bab1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-empty ng-valid-maxlength</value>
      <webElementGuid>12a82972-0921-4dbd-baaa-ec2467d4eb13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_reference&quot;)</value>
      <webElementGuid>e4b3af57-5830-456d-bad6-af2f415b7457</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer_reference']</value>
      <webElementGuid>1fc979a0-145a-465e-947f-64eab1d97506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//reference/ng-form/div/div/div/div/div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>fb306e6a-6e28-4a19-8ed6-e2d34655563a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'customer_reference' and @id = 'customer_reference' and @placeholder = 'Customer Reference']</value>
      <webElementGuid>9f1d10ad-87d5-47d3-9d25-28dce076bd3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
