<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Complete_1_2_3</name>
   <tag></tag>
   <elementGuidId>f67d4dec-4233-43ba-a77e-84e4d1bd0a99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#detailsCompleteBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='detailsCompleteBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eb01dd83-3b8a-488f-8b49-e115f73291ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>805a03d1-a06b-433f-bfcb-dd252025926d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>detailsCompleteBtn</value>
      <webElementGuid>4133f842-2013-427f-9ed5-a26231c6a714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>completeButton()</value>
      <webElementGuid>d6e5ebd5-25f7-4097-b731-c198c47ddbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                
                                Complete
                            </value>
      <webElementGuid>cf9083bf-6017-462f-88d9-09d6fd69a357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detailsCompleteBtn&quot;)</value>
      <webElementGuid>87a18515-cd1f-4161-99ac-6ed0a56981c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>49660b57-5db7-41b1-b263-5a8481e40841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b740ce47-b5aa-4b94-8ff2-dd4999dbd82d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>detailsCompleteBtn</value>
      <webElementGuid>b09c91cc-5ee7-45fe-9620-22048a578973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>completeButton()</value>
      <webElementGuid>c45c0712-06cc-4394-a958-cb6d959b52a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                
                                Complete
                            </value>
      <webElementGuid>d4969e58-0b5c-49e6-8cef-5bdb88dd2a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detailsCompleteBtn&quot;)</value>
      <webElementGuid>dc23fc8c-71e4-4144-9aaf-863363d2d29c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='detailsCompleteBtn']</value>
      <webElementGuid>802e470d-d829-4c66-b6fe-d94e7bc4091d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OS Spaces'])[1]/following::a[1]</value>
      <webElementGuid>52a30f6b-49a3-4e84-8ee9-65a7c85153ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OS Quarter'])[1]/following::a[1]</value>
      <webElementGuid>4973c65f-9d44-46ce-9bd9-fc2f0c15a414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anytime (From 09:00 - 17:00)'])[2]/preceding::a[1]</value>
      <webElementGuid>e22540ee-26c9-48ce-8d5e-eeeebc29ddab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[41]</value>
      <webElementGuid>f8d41765-196a-4fc4-aa4b-de4763c6c6e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/a</value>
      <webElementGuid>45845836-2904-47e7-b05a-c5ab047d866d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'detailsCompleteBtn' and (text() = '
                                
                                Complete
                            ' or . = '
                                
                                Complete
                            ')]</value>
      <webElementGuid>ab2c475c-b44e-46fd-8295-da3ae9922e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[42]</value>
      <webElementGuid>efbe8006-8659-45cf-b956-4d97c879b470</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
