<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Complete_1</name>
   <tag></tag>
   <elementGuidId>903f5925-80be-4814-8dbe-022b7efff928</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#referenceCompleteBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='referenceCompleteBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2c8a3e5a-76b4-43b1-8db1-60e29bdaf59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>referenceCompleteBtn</value>
      <webElementGuid>eae891f1-8398-474c-8f0c-acf8d273383f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52c136d9-2f11-4eea-b619-8579e78dc878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>completeButton()</value>
      <webElementGuid>429acf6d-bcae-4ebe-b960-f02e7d191171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            
                            Complete
                        </value>
      <webElementGuid>e42bc694-c6d6-4323-b531-dae95adbfa38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;referenceCompleteBtn&quot;)</value>
      <webElementGuid>565c2011-cf21-4f74-a9d5-5999b35bd698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2d44068f-0f0a-44a5-8764-2da3f5d2087d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>referenceCompleteBtn</value>
      <webElementGuid>3e039874-ae98-4cb0-b8f1-72d59ad1ae5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fcf82905-f098-4c9e-8f76-f391d8d5498f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>completeButton()</value>
      <webElementGuid>861637d9-bed4-4ad1-b2a5-c327889a1849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            
                            Complete
                        </value>
      <webElementGuid>e53449fe-fd3d-4682-8645-a186508b9daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;referenceCompleteBtn&quot;)</value>
      <webElementGuid>7edbe13f-3427-40f6-b22d-fc42a3559722</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='referenceCompleteBtn']</value>
      <webElementGuid>3a3c48e6-a697-45ed-826d-65b0714b6c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Number'])[1]/following::a[1]</value>
      <webElementGuid>4b9b074b-2bd7-45fa-8fee-a8610e2c986a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Reference'])[1]/following::a[1]</value>
      <webElementGuid>ab114e4c-c97a-4048-a0f2-5387c518f591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consignment Number'])[2]/preceding::a[1]</value>
      <webElementGuid>72c78e4c-97b0-4e17-9b97-29a3ccdb0a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Reference'])[2]/preceding::a[1]</value>
      <webElementGuid>bc588ad8-6268-419d-bbf8-9898357c3c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[34]</value>
      <webElementGuid>7307db83-feeb-4925-a70a-6d634e0b91de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/a</value>
      <webElementGuid>ce8a5627-a9ae-44f5-a63a-9de5444d68a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'referenceCompleteBtn' and (text() = '
                            
                            Complete
                        ' or . = '
                            
                            Complete
                        ')]</value>
      <webElementGuid>79e7885c-c07b-4c4b-93c4-915bd3b934ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[35]</value>
      <webElementGuid>e836e148-ac8b-46d4-b300-f533b56e2dd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
