<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Complete</name>
   <tag></tag>
   <elementGuidId>f5cc8728-6756-4fd6-b606-349a86be00c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#collection_deliverycompleteBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='collection_deliverycompleteBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6aa3a684-4ad3-43a0-a55a-d953cdec4a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>$ctrl.showExtra == false</value>
      <webElementGuid>3201c7e7-2a33-4c96-a707-1ba290487b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>complete()</value>
      <webElementGuid>94878a5d-23ea-4c4d-8d85-a197b5c0c6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button ng-scope</value>
      <webElementGuid>5aa9fe17-3187-48c1-aaef-107d00da4f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>collection_deliverycompleteBtn</value>
      <webElementGuid>11d0694b-099c-419e-aeb9-7cb512537b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Complete</value>
      <webElementGuid>50817e5e-d943-4838-947f-d44f454e7b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection_deliverycompleteBtn&quot;)</value>
      <webElementGuid>5125eb02-a3e6-4520-8cf0-cbde96b1d463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>079fe095-5a0c-4776-9afa-42e9c83c2ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>$ctrl.showExtra == false</value>
      <webElementGuid>03e20fb3-ca13-4258-b478-5755ab1797a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>complete()</value>
      <webElementGuid>5a11f7bb-10da-4fcc-bc35-69fe33550a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button ng-scope</value>
      <webElementGuid>59aca870-2658-4736-9bda-f73e68c5b1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>collection_deliverycompleteBtn</value>
      <webElementGuid>ecb6ce2e-1a23-4402-975c-247411e14a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Complete</value>
      <webElementGuid>2c2c77cd-faa9-49a6-b28c-edb9b69c266c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection_deliverycompleteBtn&quot;)</value>
      <webElementGuid>8da02a36-bbe5-4fbe-890c-265df14fad5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='collection_deliverycompleteBtn']</value>
      <webElementGuid>2f125861-7af7-4c53-8a02-a9e4ff7f1780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Complete')]</value>
      <webElementGuid>605bfe33-1d61-4e30-8056-357973cfd862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default Address Notes'])[1]/following::a[1]</value>
      <webElementGuid>3ba26d26-e79f-4743-8745-49eb2d635867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site Address'])[1]/following::a[1]</value>
      <webElementGuid>f4dd86ab-49fb-4b53-a8e8-a58407f72530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Complete']/parent::*</value>
      <webElementGuid>08009761-ffc4-4b93-bbf3-75ac2800e23b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[32]</value>
      <webElementGuid>b99935ff-a9a4-4e84-a6d6-f57a237c119f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ptapp-address-buttons/div/a</value>
      <webElementGuid>a0ba7ec6-0153-42fe-8572-3c871d3a9d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'collection_deliverycompleteBtn' and (text() = ' Complete' or . = ' Complete')]</value>
      <webElementGuid>77e6e7d4-26ea-4f2c-be2c-ac74053cbaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[33]</value>
      <webElementGuid>2a896ac8-6c9e-4a9f-b3d9-6f35c2ea294a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
