<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Complete_1_2</name>
   <tag></tag>
   <elementGuidId>e332e307-cbaa-435c-aa7d-6c38b6a40381</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#delivery_deliverycompleteBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='delivery_deliverycompleteBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fef90b0b-357e-49e9-827f-8d1a6c9afda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>$ctrl.showExtra == false</value>
      <webElementGuid>da622e38-efb0-4ab5-8f11-52f6990cf73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>complete()</value>
      <webElementGuid>f4c38b8c-ba6c-4a57-9f3e-37679f5a2ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button ng-scope</value>
      <webElementGuid>5cc62391-d758-4ebc-8802-c1d5a655c834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery_deliverycompleteBtn</value>
      <webElementGuid>58b3dad6-1c1d-495a-a9c5-0cad28683883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Complete</value>
      <webElementGuid>7045a087-5dce-468f-9eef-9b8af617dca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery_deliverycompleteBtn&quot;)</value>
      <webElementGuid>0782579e-e34a-43a4-88b2-e863fbec91b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32230d2d-a803-4c73-bca2-ac0220b92c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>$ctrl.showExtra == false</value>
      <webElementGuid>41c628f6-e1f8-446e-85ac-57e1d144e356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>complete()</value>
      <webElementGuid>7a9dedc7-2573-4e4c-9271-f837eb02c0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button ng-scope</value>
      <webElementGuid>b92e350c-4180-40f4-9c65-afcc6be53fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery_deliverycompleteBtn</value>
      <webElementGuid>9b379d3e-1e5a-4fb9-b239-cac6ee07cdb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Complete</value>
      <webElementGuid>4216fd98-681e-4d4e-81a4-f8cf289e3249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery_deliverycompleteBtn&quot;)</value>
      <webElementGuid>5b69fafd-bfe4-4325-89a7-da8683ae4021</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='delivery_deliverycompleteBtn']</value>
      <webElementGuid>e7c2a66f-3154-4bd2-bbae-b1bc7283f4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Complete')])[2]</value>
      <webElementGuid>774252f0-2ffe-424d-8544-5289edcdfca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember This Address'])[1]/following::a[1]</value>
      <webElementGuid>f7f454fd-03a1-49e3-bc6f-71944e0e5c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Address'])[1]/following::a[2]</value>
      <webElementGuid>781180f4-a24c-408f-8359-6a8a5a547ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[39]</value>
      <webElementGuid>0745f996-4975-4293-bca4-31196ac07544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ptapp-address-buttons/div/a[3]</value>
      <webElementGuid>e459e0f7-496b-4111-97bf-a8529f31139c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'delivery_deliverycompleteBtn' and (text() = ' Complete' or . = ' Complete')]</value>
      <webElementGuid>426d7818-6381-4a50-aaa7-63b4ac04ad7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit This Address'])[1]/following::a[1]</value>
      <webElementGuid>a506cf86-4b03-41a1-906b-ef57f0a1e4b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[40]</value>
      <webElementGuid>fc68e8ec-e913-4c56-9f24-685d1603ac14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
