<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save</name>
   <tag></tag>
   <elementGuidId>43261966-112e-40e5-a1d8-0e531f748007</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#saveForm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='saveForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>deaef8b4-39f1-4bd9-bcba-a3ff729f5c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'button' : buttonsEnabled , 'button button--disabled' : !buttonsEnabled }</value>
      <webElementGuid>8d9da842-6342-431e-ac8e-8aba7ede8a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saveForm</value>
      <webElementGuid>52e9acea-06a4-436d-a52f-17b1ddedc532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>save(false)</value>
      <webElementGuid>84c259f4-6372-421b-8f09-eedd93155b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4c032f62-f272-433c-8c44-2546bdb9b119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    
                    Save
                </value>
      <webElementGuid>6183932d-9acd-46b6-a623-71aad06a142e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveForm&quot;)</value>
      <webElementGuid>bd75ed73-366b-4128-84ff-b7e55a908412</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='saveForm']</value>
      <webElementGuid>795e2d5b-d358-4bab-b849-d54e37850200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Paperwork Required'])[1]/following::a[2]</value>
      <webElementGuid>746dec30-3ac0-47a3-9804-1230243d8b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vigo Software Ltd'])[1]/preceding::a[2]</value>
      <webElementGuid>dc196a33-87cd-412b-bda2-3346fc3f10c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>74729884-9af6-4f01-a243-434dd0ea3114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//buttons/div/div/div/div/a[2]</value>
      <webElementGuid>be798b4b-8641-4dab-907e-b1a626ce0bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'saveForm' and (text() = '
                    
                    Save
                ' or . = '
                    
                    Save
                ')]</value>
      <webElementGuid>64897497-654b-4cd1-8765-812ffd8b2d61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
