<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Full_details_full</name>
   <tag></tag>
   <elementGuidId>bb854d75-29bf-4427-8a3a-9c279cf8f876</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#details_full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='details_full']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49113ed2-cf4b-40ca-988e-7f196f6d8d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mask-details-short details-group ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>42d69ff1-0c9c-48ff-a246-9d46681695ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>040cd42d-cae0-4a9b-a607-4a2f2124a364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details_full</value>
      <webElementGuid>94ec11ff-08a7-4e69-8c19-f143942cae3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details_full</value>
      <webElementGuid>2dcb0dae-ea2e-4dd3-984d-8496816a816b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>spaces.full</value>
      <webElementGuid>489a1e30-94c8-4b05-8800-a6319c713567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>spacesUpdated('full')</value>
      <webElementGuid>19eef634-4baa-4f3a-ac37-85deef9f4361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>77f301ef-e1eb-4900-9b2b-f84d7d41fac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details_full&quot;)</value>
      <webElementGuid>86c776e0-4a6d-484c-a4ea-227eca056022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c0ccee9-6c51-4da0-ba1e-e44d2d026bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mask-details-short details-group ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>85f93cf2-c540-40fd-82ee-9838a612e78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f094462-d770-4426-853c-74272b2f4e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details_full</value>
      <webElementGuid>9604f569-0afc-4a1d-baf1-b7ca0013c2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details_full</value>
      <webElementGuid>32efb67b-e814-4242-8df7-e2c5b0071c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>spaces.full</value>
      <webElementGuid>bdcc1f56-8e2d-409d-b785-84f4917cb851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>spacesUpdated('full')</value>
      <webElementGuid>94801177-20ec-4957-8074-de646a68dc46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1a0c8231-26f3-4d7d-8b0a-066fbbdb89e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details_full&quot;)</value>
      <webElementGuid>0949dc11-3f8f-4eee-8246-1237dc252ac5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='details_full']</value>
      <webElementGuid>b16519a6-d7fb-4cfc-bc12-14c98a9d01e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ptapp-spaces/div/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>53390c50-0a4d-4166-b7f7-35d2ab58e4e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'details_full' and @id = 'details_full']</value>
      <webElementGuid>a13a7e6e-1980-4526-baab-e945bc875e26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
