<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__collection_date</name>
   <tag></tag>
   <elementGuidId>e3a76e73-dea2-41a9-8345-6ad87084ef1a</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'collection_date' and @id = 'collection_date' and @placeholder = 'Collection Date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#collection_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='collection_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5517ba7b-ac9e-4602-a4d5-0c5828420b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d703f254-b917-417e-97b4-0052beccaabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>collection_date</value>
      <webElementGuid>bec4fd51-3a2a-415b-85d9-d4545e5202d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>collection_date</value>
      <webElementGuid>f5d4e5de-0bac-4580-84c4-a363c759106a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Collection Date</value>
      <webElementGuid>f71db715-08b9-4486-8b0f-ed4e06cef317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>address.date</value>
      <webElementGuid>ffa688c1-069d-4aca-a44f-8acfa42245a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>collectionDateChanged()</value>
      <webElementGuid>9a38153f-482e-4de6-8ab7-e50eb6d56ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>8004b955-35e8-4bb4-85e9-d0a4a9db31f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dateMask ng-pristine ng-untouched ng-valid ng-not-empty ng-valid-required ng-valid-maxlength</value>
      <webElementGuid>8dc72cf0-52ec-48af-9ea7-1824ed24becb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection_date&quot;)</value>
      <webElementGuid>dd4bb00e-13b4-46a8-9fd4-07a9c4f60db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2d49817-5623-466f-b89f-f6ea02e44fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fcc0c814-1796-464e-9ede-e84c90afe030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>collection_date</value>
      <webElementGuid>86ebde5e-7830-4184-aac1-53759b256008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>collection_date</value>
      <webElementGuid>707f0960-8544-491b-abfa-9f200b7087bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Collection Date</value>
      <webElementGuid>80afd15a-0b11-4ee8-b2bb-a3f9b9166440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>address.date</value>
      <webElementGuid>ce0a9fb9-485f-4f4d-a950-00f44a012e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>collectionDateChanged()</value>
      <webElementGuid>62921f1d-e344-4f59-bbc5-57b02a179a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>86608404-7ca9-492e-aec8-c045cfaf9e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dateMask ng-pristine ng-untouched ng-valid ng-not-empty ng-valid-required ng-valid-maxlength</value>
      <webElementGuid>e57916b1-cb0d-4ccb-b832-59e2577fea83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection_date&quot;)</value>
      <webElementGuid>3c88f155-a380-44cc-af8a-cfb6728a681c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='collection_date']</value>
      <webElementGuid>2fefa079-0f9a-4297-9e2d-6364937dac66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>6ddd6608-2f3b-4199-9dba-bd46c52ece4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'collection_date' and @id = 'collection_date' and @placeholder = 'Collection Date']</value>
      <webElementGuid>90bfb796-0c16-462c-8a21-4c615906d693</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
