<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fields_addr1</name>
   <tag></tag>
   <elementGuidId>eba6f5b7-8e2e-4c63-9af7-9129d058d3c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#delivery_delivery_fields_addr1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='delivery_delivery_fields_addr1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93230815-dee5-4b28-b93d-79d7bd03332e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fba9f9e6-50ef-405a-a2a6-f9bafcc904d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fields_addr1</value>
      <webElementGuid>e7f47af0-4572-476d-8a9e-725055c649d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/[A-Za-z0-9/*-_.,&amp;'()+/]+$/</value>
      <webElementGuid>59579b2c-3387-4cf0-b8b0-c3e7b5f0f90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery_delivery_fields_addr1</value>
      <webElementGuid>663719e8-e091-45ba-bebf-3c136cbdc262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>House No. / Property Name *</value>
      <webElementGuid>c40832a4-bba3-43c5-85c5-00247cea79e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>fields.add1</value>
      <webElementGuid>70d73d76-324f-4da0-8e8b-b2dd18eeec48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>f113ba88-9218-4f76-b1b3-bd1b9225df9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>validation.fields_addr1.required</value>
      <webElementGuid>c72cde01-b554-409f-a310-7ae365015dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-pattern ng-valid-maxlength</value>
      <webElementGuid>092a9def-37fc-4f43-94d1-02071d5f6100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>50e34c82-622a-4963-923b-959725b38537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery_delivery_fields_addr1&quot;)</value>
      <webElementGuid>1b121f24-7497-461d-8963-3f1a9fbda584</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='delivery_delivery_fields_addr1']</value>
      <webElementGuid>5b814e8f-2f30-4629-a877-454d06a6e198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ptapp-address-master/ng-form/div/div[2]/div/div/div[2]/ptapp-address-fields/ng-form/div/div/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>4543567b-cb39-429b-9470-6255892f76dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fields_addr1' and @id = 'delivery_delivery_fields_addr1' and @placeholder = 'House No. / Property Name *']</value>
      <webElementGuid>3db51b89-ce45-455c-841e-35dc97f43d28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
