<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_28062023290620233006202303072023</name>
   <tag></tag>
   <elementGuidId>1d87af27-4565-4b4a-9be7-3129b3ba1991</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#delivery_specific_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='delivery_specific_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dff6eb41-6966-4417-8e87-25e3d5c521d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>delivery_specific_date</value>
      <webElementGuid>3d98fa08-4bdd-4809-b26b-533d2065044d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery_specific_date</value>
      <webElementGuid>c8f4a286-1e25-4de9-a8be-60054c4599df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>specificDate</value>
      <webElementGuid>f9c375ee-b1af-4c86-b134-f823445e6e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>specificDateUpdated()</value>
      <webElementGuid>16a173be-b69d-46b0-9ea4-4325e7b49296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>1087234f-ef1a-4667-a67d-d320c40e794d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                28/06/202329/06/202330/06/202303/07/2023
                            </value>
      <webElementGuid>06217d65-a9e3-45cd-acae-a98cfeddbe8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery_specific_date&quot;)</value>
      <webElementGuid>eeea9bb9-dc83-459f-aea7-658a1e862383</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='delivery_specific_date']</value>
      <webElementGuid>045ccc93-80a3-47a2-a2cd-dde2d7cedec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Date'])[1]/following::select[1]</value>
      <webElementGuid>96af6122-4044-4a20-a0b7-5e8cd4b1976d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service'])[1]/following::select[2]</value>
      <webElementGuid>6f707c83-27c1-4e84-9d09-dd145aeabcf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Time'])[1]/preceding::select[1]</value>
      <webElementGuid>6af95112-f360-4de5-a951-009e9f423e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter time between'])[1]/preceding::select[2]</value>
      <webElementGuid>75ccc7dc-3f9f-4ebb-9c07-a51c52855496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/select</value>
      <webElementGuid>9e3056f4-a1a0-4ee8-b947-8a39a452a59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'delivery_specific_date' and @id = 'delivery_specific_date' and (text() = '
                                28/06/202329/06/202330/06/202303/07/2023
                            ' or . = '
                                28/06/202329/06/202330/06/202303/07/2023
                            ')]</value>
      <webElementGuid>81073218-5e13-4b6f-a4cb-98cf62d88fe2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
