<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_04072023050720230607202307072023</name>
   <tag></tag>
   <elementGuidId>6f53e690-3669-4beb-ae6c-2f43b2180ec7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#delivery_specific_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='delivery_specific_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>017beda4-af21-4f31-ba70-625e2062bb68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>delivery_specific_date</value>
      <webElementGuid>c9047045-abe4-43c5-a295-20ec2ef4864c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery_specific_date</value>
      <webElementGuid>74f09083-41df-4b06-899d-46680eaef904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>specificDate</value>
      <webElementGuid>99b26a5f-68cf-4108-80f4-15f5994a879a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>specificDateUpdated()</value>
      <webElementGuid>f101c6e1-fee8-45b3-8f1c-e74652ad8945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>8669a030-120a-4581-9a70-c9d3ae21502e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                04/07/202305/07/202306/07/202307/07/2023
                            </value>
      <webElementGuid>84472a23-58b9-453d-addd-969f6b10d20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery_specific_date&quot;)</value>
      <webElementGuid>42ac5409-7940-4f94-a273-05b70f407fad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='delivery_specific_date']</value>
      <webElementGuid>616a7dbb-9168-4ba6-a0df-562d1c3dc90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Date'])[1]/following::select[1]</value>
      <webElementGuid>775ae68a-d438-4998-ab96-18d0fab3f461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service'])[1]/following::select[2]</value>
      <webElementGuid>8d2b7d5e-cfee-49d4-9f91-466bed8a7e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Time'])[1]/preceding::select[1]</value>
      <webElementGuid>c36a06aa-44e5-4fc7-8f9b-745fa1639a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter time between'])[1]/preceding::select[2]</value>
      <webElementGuid>7b64e681-4898-4ed3-89b5-46371d48ff0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/select</value>
      <webElementGuid>6e0e6134-c845-4516-9953-a1aacab97ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'delivery_specific_date' and @id = 'delivery_specific_date' and (text() = '
                                04/07/202305/07/202306/07/202307/07/2023
                            ' or . = '
                                04/07/202305/07/202306/07/202307/07/2023
                            ')]</value>
      <webElementGuid>9c95cf8f-de43-4297-bb04-92e769c13fcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
