<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CollectionCompleteBtn</name>
   <tag></tag>
   <elementGuidId>22cc7825-100d-4efc-b4db-1284bfaef34c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='collection_deliverycompleteBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#collection_deliverycompleteBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ec9dc33d-38c3-46a2-b5ea-babd4eef7ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>$ctrl.showExtra == false</value>
      <webElementGuid>cd2c6940-c746-497b-adae-dee3e8c5d92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>complete()</value>
      <webElementGuid>a7c9f77c-ee74-444f-a309-50141b2c1461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button ng-scope</value>
      <webElementGuid>7cf33738-7704-477a-baf6-350033337bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>collection_deliverycompleteBtn</value>
      <webElementGuid>3e210228-e34b-4d09-8676-4db26c586f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Complete</value>
      <webElementGuid>e25beafd-4b6a-4080-ba01-92e12551d256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection_deliverycompleteBtn&quot;)</value>
      <webElementGuid>007d1526-ed24-4f07-b753-b0f9a6ca16e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='collection_deliverycompleteBtn']</value>
      <webElementGuid>870ba474-f9fb-44b8-92aa-d40c1656a121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Complete')]</value>
      <webElementGuid>8f498659-6d24-49cd-8ae3-8a8b94575a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default Address Notes'])[1]/following::a[1]</value>
      <webElementGuid>d8405eac-d71f-4b85-9e3e-f5572dbfb40b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site Address'])[1]/following::a[1]</value>
      <webElementGuid>3865bf43-ad09-4853-84fc-4cff0add1b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Complete']/parent::*</value>
      <webElementGuid>5c698239-75b7-4014-a0b2-a358c69e4ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[32]</value>
      <webElementGuid>bbfc8322-3c57-43ab-982e-c3a5cbfe6274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ptapp-address-buttons/div/a</value>
      <webElementGuid>d03ee8cb-717a-4649-a1f0-8f751390f53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'collection_deliverycompleteBtn' and (text() = ' Complete' or . = ' Complete')]</value>
      <webElementGuid>383c6bf6-6204-4470-8d4a-53bf5524fc7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
