<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_collection_date</name>
   <tag></tag>
   <elementGuidId>48c229b6-ad90-4c25-8f66-c3d8d9e45f98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='collection_date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#collection_date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b3d5125-b904-4bcf-8f18-d26e6238112d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8cb8419b-52c9-4d0d-af20-8fbce2f06070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>collection_date</value>
      <webElementGuid>905be6c3-d3c2-4346-a1ec-cce09d280e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>collection_date</value>
      <webElementGuid>10dd1a6f-956f-4106-a85e-f716736b8699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Collection Date</value>
      <webElementGuid>3a6d8548-3248-4a3a-9281-d3dffa4dcf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>address.date</value>
      <webElementGuid>897430a5-c2dd-495a-a454-5fe67921eb04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>collectionDateChanged()</value>
      <webElementGuid>2d7ce67f-5f47-4c59-9b27-6f3c95403c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>d0fbc13a-e377-4d5c-a282-aaf88d069105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dateMask ng-pristine ng-untouched ng-valid ng-not-empty ng-valid-required ng-valid-maxlength</value>
      <webElementGuid>793296e4-3bfc-4fc9-90f4-57b9a7b1f7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Use the arrow keys to pick a date</value>
      <webElementGuid>36628fd4-2fa9-449c-8360-70f05bbc5b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection_date&quot;)</value>
      <webElementGuid>792cca37-5b2c-49bf-9725-ba11083de5b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='collection_date']</value>
      <webElementGuid>798298f8-df87-444d-b122-145f86272d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>49ee8751-21a0-47dc-b807-cb61c40c0bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'collection_date' and @id = 'collection_date' and @placeholder = 'Collection Date']</value>
      <webElementGuid>e99ca509-56d3-4969-bb75-985019db7dff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
