<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__collection_date</name>
   <tag></tag>
   <elementGuidId>99d467c1-8b35-44ab-9026-83c3f930765b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#collection_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='collection_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a62d9f7-6737-412a-8af4-65ac6340fcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>82ce3b83-7b04-4d09-9a9c-bdc3f0c04d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>collection_date</value>
      <webElementGuid>8d4b9494-b37d-4661-8461-71644c5f7bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>collection_date</value>
      <webElementGuid>6defebbb-0266-4f10-a3b6-ce7a3d8dd6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Collection Date</value>
      <webElementGuid>6ad1b15e-e382-42fb-8c76-3013550622a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>address.date</value>
      <webElementGuid>69a1acc2-2f0b-4b3c-9944-4724610a247a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>collectionDateChanged()</value>
      <webElementGuid>0f9f7f8e-2377-4739-ba40-64b8c404f6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>d1eadc07-66c2-49da-9caf-e1c3ad556931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dateMask ng-pristine ng-untouched ng-valid ng-not-empty ng-valid-required ng-valid-maxlength</value>
      <webElementGuid>75fa2bc2-72e6-472a-828e-089f34a3738f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection_date&quot;)</value>
      <webElementGuid>413d8d6e-3092-4b06-a897-24fd01b7f297</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='collection_date']</value>
      <webElementGuid>3b5bd6db-3ab8-4987-b8d6-68f1e507d9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>48ec3653-7a78-4a51-997a-d509df024a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'collection_date' and @id = 'collection_date' and @placeholder = 'Collection Date']</value>
      <webElementGuid>effa61e9-0838-4398-87fe-ea7dc313a93c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
