<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>customerLinkIdentifier</name>
   <tag></tag>
   <elementGuidId>e295ce48-0d45-4db9-9487-5351688741a3</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cust-99cashac']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#{'cust-'+custId}</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '${custId}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4f3474fc-94b5-4a3e-8906-08cb0083e9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>${custId}</value>
      <webElementGuid>9ae4341c-c515-47f6-a687-512b7fd5f17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/?module=customer-config&amp;custId=68629&amp;shortCompany=99cashac</value>
      <webElementGuid>e81e0451-5ad5-4889-af94-4020f6120e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>7cfca9d4-66bf-4672-ad7c-be716bbbce79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>99cashac</value>
      <webElementGuid>875971f5-e645-4868-9b4b-2854ae961382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cust-99cashac&quot;)</value>
      <webElementGuid>e21c66e3-e20e-45c0-966e-c6294efdd472</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cust-99cashac']</value>
      <webElementGuid>220d2bb5-2b4a-44c0-9d1d-c9893809bab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'99cashac')]</value>
      <webElementGuid>015503df-fa3c-4d2b-8e76-79069f5b2969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='customerservice@interhaul.co.uk'])[1]/following::a[1]</value>
      <webElementGuid>ee5931c0-41ef-4ffd-b304-dd0ee3ec828c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CUSTOMERSERVICES@INTERHAUL.CO.UK'])[1]/following::a[2]</value>
      <webElementGuid>f3ed3dcf-58a6-46c5-b259-1a6010f59528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='interhaultemp@gmail.com'])[1]/preceding::a[1]</value>
      <webElementGuid>86f7e0ea-0e1f-4b56-92c3-520edcc3ced5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@TURF'])[1]/preceding::a[1]</value>
      <webElementGuid>cef7ec8d-98e6-48ce-b0d1-1a1daf1811cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='99cashac']/parent::*</value>
      <webElementGuid>db34854b-b02f-46f3-89ac-eb6ac24b6940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/?module=customer-config&amp;custId=68629&amp;shortCompany=99cashac')]</value>
      <webElementGuid>0016cce3-f49c-4b4e-a9fb-2766727d5c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/a</value>
      <webElementGuid>c42ffb6c-9d8a-4c63-a127-140565693f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cust-99cashac' and @href = '/?module=customer-config&amp;custId=68629&amp;shortCompany=99cashac' and (text() = '99cashac' or . = '99cashac')]</value>
      <webElementGuid>382eebc0-b607-4e6f-a6f5-1886f86fb912</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
